apiVersion: v1
kind: Secret
metadata:
  name: backend-secret
  namespace: muchtodo
type: Opaque
stringData:
  MONGO_URI: mongodb://muchtodo:muchtodo@mongodb.muchtodo.svc.cluster.local:27017/much_todo_db?authSource=admin
  JWT_SECRET_KEY: change-me-before-production
