#!/bin/bash

set -e

IMAGE=$1

INSTANCE_IDS=$(aws ec2 describe-instances \
  --region us-east-1 \
  --filters "Name=instance-state-name,Values=running" \
            "Name=tag:Name,Values=dev-backend*" \
  --query "Reservations[*].Instances[*].InstanceId" \
  --output text)

echo "Deploying image: $IMAGE"
echo "Instances: $INSTANCE_IDS"

aws ssm send-command \
  --region us-east-1 \
  --instance-ids $INSTANCE_IDS \
  --document-name "AWS-RunShellScript" \
  --comment "Deploy backend container" \
  --parameters '{
    "commands": [
      "aws ecr get-login-password --region us-east-1 | docker login --username AWS --password-stdin 093796422475.dkr.ecr.us-east-1.amazonaws.com",
      "docker pull '"$IMAGE"'",
      "docker stop backend || true",
      "docker rm backend || true",
      "docker run -d --name backend -p 8080:8080 -e PORT=8080 -e MONGO_URI=\"mongodb+srv://YOUR_URI\" -e DB_NAME=\"much_todo_db\" -e JWT_SECRET_KEY=\"dev-secret\" '"$IMAGE"'"
    ]
  }'